packages:
  ids: !include ./base/ids.yaml
  esp: !include ./base/esp-s3.yaml

substitutions:
  board_name: nora_room_aq
  board_comment: ESP32 Air Quality Tracker
  board_id: $nora_room_air_quality_board_id
  organic_compounds_sensor_id: $nora_organic_compounds_1_sensor_id
  air_temperature_sensor_id: $nora_air_temperature_1_sensor_id
  air_pressure_sensor_id: $nora_air_pressure_1_sensor_id
  air_humidity_sensor_id: $nora_air_humidity_1_sensor_id

i2c:
  sda: GPIO8
  scl: GPIO9
  scan: true
  id: bus_a
  frequency: 15khz

sensor:
  - platform: ags10
    id: organic_compounds_sensor
    update_interval: 15min
    address: 0x1A
    tvoc:
      name: organic_compounds_sensor
      on_value:
        then:
          - lambda: |-
              id(mqtt_event_helper_float)(id(make_sensor_topic)($organic_compounds_sensor_id, "organic_compounds"), x, "$organic_compounds_sensor_id");
  - platform: bme280_i2c
    address: 0x76
    update_interval: 15min
    iir_filter: 16x
    temperature:
      id: air_temp
      on_value:
        then:
          - lambda: |-
              id(mqtt_event_helper_float)(id(make_sensor_topic)($air_temperature_sensor_id, "air_temperature"), x, "$air_temperature_sensor_id");
    pressure:
      id: air_pressure
      on_value:
        then:
          - lambda: |-
              id(mqtt_event_helper_float)(id(make_sensor_topic)($air_pressure_sensor_id, "air_pressure"), x, "$air_pressure_sensor_id");
    humidity:
      id: air_humidity
      on_value:
        then:
          - lambda: |-
              id(mqtt_event_helper_float)(id(make_sensor_topic)($air_humidity_sensor_id, "air_humidity"), x, "$air_humidity_sensor_id");
