substitutions:
  security_board_id: '1'
  daylight_tracker_1_board_id: '2'
  car_garage_door_board_id: '3'
  front_house_environment_board_id: '4'
  downstairs_air_board_id: '5'
  nora_room_air_quality_board_id: '6'
  front_door_sensor_id: '1'
  interior_garage_door_sensor_id: '2'
  dining_room_slider_sensor_id: '3'
  stair_side_slider_sensor_id: '4'
  chimney_side_slider_sensor_id: '5'
  tv_slider_sensor_id: '6'
  car_garage_door_sensor_id: '7'
  storage_garage_door_sensor_id: '8'
  downstairs_air_temp_sensor_id: '9'
  downstairs_air_pressure_sensor_id: '10'
  downstairs_air_humidity_sensor_id: '11'
  daylight_tracker_1_lux_sensor_id: '12'
  nora_organic_compounds_1_sensor_id: '13'
  nora_air_temperature_1_sensor_id: '14'
  nora_air_pressure_1_sensor_id: '15'
  nora_air_humidity_1_sensor_id: '16'
  front_house_environment_temp_sensor_id: '17'
  front_house_environment_humidity_sensor_id: '18'
  front_house_environment_pressure_sensor_id: '19'
  front_house_environment_garage_temp_sensor_id: '20'
  plant_water_test_sensor_id: '99'