mqtt:
  id: mqtt_client
  broker: !secret mqtt_broker
  port: 1883
  username: !secret mqtt_username
  password: !secret mqtt_password
  client_id: $board_name
  discovery: false
  clean_session: false
  enable_on_boot: true
  wait_for_connection: true
  topic_prefix: "warbreaker"
  on_connect:
    then:
      - lambda: |-
          id(mqtt_event_helper_str)(id(make_board_topic)("mqtt"), std::string("Connected"), "");
  idf_send_async: true
  reboot_timeout: 2min
  keepalive: 5s