mqtt_broker: "192.168.2.27"
mqtt_username: "ha-mqtt"
mqtt_password: "yiiJYKaPq9Y7UUhG694bK5Po43o9gCuu"
recovery_ssid: "esp_recovery"
recovery_password: "WompWomp!"
wifi_ssid: "Phantom-IoT"
wifi_password: "AllYourIotAreBelongToUs"
