wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true
  output_power: 20.0dBm
  power_save_mode: none
  ap:
    ssid: !secret recovery_ssid
    password: !secret recovery_password

captive_portal:

mdns:
  disabled: false

time:
  - platform: sntp
    timezone: "Etc/Utc"
    id: sntp_time
    servers:
     - 0.pool.ntp.org
     - 1.pool.ntp.org
     - 2.pool.ntp.org
    update_interval: 360min
    on_time_sync:
      then:
        # Update last restart time, but only once.
        - if:
            condition:
              lambda: 'return id(device_last_restart).state == "";'
            then:
              - text_sensor.template.publish:
                  id: device_last_restart
                  state: !lambda 'return id(sntp_time).now().strftime("%a %d %b %Y - %I:%M:%S %p");'
    on_time:
      - seconds: 0
        minutes: '*'
        then:
          - lambda: |-
              id(mqtt_heartbeat)();
