name: Build and Publish Docker Images

on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push mqtt-ingestor image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: src/cmd/mqtt-ingestor/Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository }}/mqtt-ingestor:latest

      - name: Build and push web image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: src/cmd/web/Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository }}/web:latest

      - name: Upload Docker images as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: docker-images
          path: |
            src/cmd/mqtt-ingestor/Dockerfile
            src/cmd/web/Dockerfile
